# Generated by Django 3.1.4 on 2020-12-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'categorías',
            },
        ),
    ]
