# Generated by Django 3.1.4 on 2020-12-12 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pachaqtec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=240)),
                ('celular', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_cupon', models.CharField(max_length=30)),
                ('importe_cupon', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('porcentaje_cupon', models.PositiveSmallIntegerField()),
                ('fecha_fin', models.DateField()),
                ('en_uso', models.BooleanField(default=False)),
                ('por_categoria', models.BooleanField(default=False)),
                ('por_curso', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.TextField()),
                ('resumen', models.TextField()),
                ('dirigido_a', models.TextField(blank=True, null=True)),
                ('otorga', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pachaqtec.categoria')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
