# Generated by Django 3.1.4 on 2020-12-12 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pachaqtec', '0002_auto_20201210_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.TextField()),
                ('resumen', models.TextField()),
                ('dirigido_a', models.TextField(blank=True, null=True)),
                ('otorga', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pachaqtec.categoria')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
