# Generated by Django 3.1.4 on 2020-12-17 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pachaqtec', '0002_auto_20201215_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('frecuencia', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pachaqtec.cursos')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
    ]
