# Generated by Django 3.1.4 on 2020-12-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachaqtec', '0003_alumno_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(db_table='pachaqtec_matricula', to='pachaqtec.Cursos'),
        ),
    ]
