# Generated by Django 3.1.4 on 2020-12-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachaqtec', '0004_auto_20201212_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cupon',
            field=models.ManyToManyField(limit_choices_to={'por_categoria': True}, to='pachaqtec.Cupon'),
        ),
    ]
