# Generated by Django 3.1.4 on 2020-12-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachaqtec', '0005_categoria_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='cupon',
            field=models.ManyToManyField(limit_choices_to={'por_curso': True}, to='pachaqtec.Cupon'),
        ),
    ]
