# Generated by Django 3.1.4 on 2020-12-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachaqtec', '0005_cursos_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='cupon',
            field=models.ManyToManyField(blank=True, to='pachaqtec.Cupon'),
        ),
    ]
